# Holds the level layout in a list of strings.

level = [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"W                                                W",
"W                                                W",     
"W                                                W",
"W                                                W",
"W                                    W           W",
"W                                    W           W",
"W  W         WWWWWWWWWW              WWWWWWWWWWWWW",
"W            W                                   W",
"W            W                                   W",
"WWWWWWWWWWWWWW                                   W",
"W                                                W",
"W                                                W",
"W                                                W",
"W                                                W",
"W                 WWWWWWWWWWWWWWWWWW             W", 
"W                 W                              W", 
"W                 W                              W",
"WWWWWWWW          W       W                      W",
"W                 W                              W",
"W                 WWWWWWW                        W",
"W                 W                              W",
"W                 W               W              W",
"W                 W               W              W",                                             
"WWWWWWWW          W               W              W",
"W                 W               W              W",
"W                 W               W              W",
"W                 W               W              W",
"W                 W               W              W",
"W                 W             WWWWWW           W",
"W       W         W            W                 W",
"W                              W                 W",
"W                              W                 W",
"W                              W                 W", 
"W                              W                 W",
"W                              W                 W",                                               
"WWWWWWWWWWWWWWWWWWWWWWWWEWWWWWWWWWWWWWWWWWWWWWWWWW",
]