# level = [
# "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
# "W                                                W",
# "W                                                W",     
# "W                                                W",
# "W                                                W",
# "W                                    W           W",
# "W                                    W           W",
# "W  W         WWWWWWWWWW              WWWWWWWWWWWWW",
# "W            W                                   W",
# "W            W                                   W",
# "WWWWWWWWWWWWWW                                   W",
# "W                                                W",
# "W                                                W",
# "W                                                W",
# "W                                                W",
# "W                 WWWWWWWWWWWWWWWWWW             W", 
# "W                 W                              W", 
# "W                 W                              W",
# "WWWWWWWW          W       W                      W",
# "W                 W                              W",
# "W                 WWWWWWW                        W",
# "W                 W                              W",
# "W                 W               W              W",
# "W                 W               W              W",                                             
# "WWWWWWWW          W               W              W",
# "W                 W               W              W",
# "W                 W               W              W",
# "W                 W               W              W",
# "W                 W               W              W",
# "W                 W             WWWWWW           W",
# "W       W         W            W                 W",
# "W                              W                 W",
# "W                              W                 W",
# "W                              W                 W", 
# "W                              W                 W",
# "W                              W                 W",                                               
# "WWWWWWWWWWWWWWWWWWWWWWWWEEEWWWWWWWWWWWWWWWWWWWWWWW",
# ]

level = [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"W                                    W           W",
"W                                    W           W",     
"W                                    W           W",
"W          WWWWWWWWWWWW              W           W",
"W          W          W              W           W",
"W          W          W              W           W",
"WWWWWWWWWWWW          W         WWWWWWW          W",
"W                              W                 W",
"W                              W                 W",
"W                              W                 W",
"W          WWW         WWWWWWWWWWWWWWWWWW        W",
"W                                                W",
"W                                                W",
"W                                                W",
"W                                                W", 
"W            WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW", 
"W                                                W",
"W                                                W",
"W                                                W",
"W            W                 WWWWWWWWWWWWWWWWWWW",        
"W            W                 W                 W",
"W            W                 W                 W",
"W            W                 W                 W",                                             
"W            WWWWWWWWWWWWWWWWWWW                 W",
"W                                                W",
"W                                                W",
"W                                                W",
"WWWWWWWWWWWWWWW                  WWWWWWWWWWWWWWWWW",
"W             W                                  W",
"W             W                                  W",
"W             WWWWWWWWWW                         W",
"W                                 W              W",
"W                                 W              W", 
"W                                 W              W",
"W                                 W              W",                                               
"WWWWWWWWWWWWWWWWWWWWWWWWEEEWWWWWWWWWWWWWWWWWWWWWWW",
]
